services:
  - name: expert-session-booking
    type: web
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: AUTO_SEED
        value: true
      - key: CLIENT_URL
        sync: false
      - key: MONGODB_URI
        sync: false
